version: '3.8'

services:
  db:
    image: mysql:8.0.37
    container_name: 50pvt_db
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: '50pvt_db'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
