version: '3.8'

services:
  db:
    image: mysql:8.0.36
    container_name: 50pvt_db
    environment:
      MYSQL_ROOT_PASSWORD: 'zxcv1234!'
      MYSQL_DATABASE: '50pvt_db'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
